export default{
    'population_all': {
        id: 2,
        theme: "average age",
        subject: "population",
        topic: "population",
        topicLong: "resident population",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "populated",
        synonym: "headcount",
        verb: {
            positive: "grow",
            negative: "shrink",
            },
        noun: {
            positive: "grow",
            negative: "shrink",
            },
        alternative: "density",
    },
    'density_all': {
        id: 2,
        theme: "average age",
        topic: "population density",
        topicLong: "people per hectare",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "density",
        synonym: "population density",
        verb: {
            positive: "increase",
            negative: "decrease",
            },
        noun: {
            positive: "increase",
            negative: "decrease",
            },    
        alternative: "population",
    },
    'agemed_all': {
        id: 2,
        theme: "average age",
        subject: "average age",
        topic: "age",
        topicLong: "average age",
        topicMed: "average age",
        topicMed2: "average age",
        adjective: "old",
        synonym: "average age",
        verb: {
            positive: "shift",
            negative: "shift",
            },
        noun: {
            positive: "shift",
            negative: "shift",
            },
        alternative: "age10yr",
    },
    'health_good': {
        id: 1,
        theme: 'well-being',
        subject: "health",
        topic: "health",
        topicLong: "residents describing their health as good",
        topicMed: "in good health",
        topicMed2: "in good health",
        adjective: "healthy",
        synonym: "healthy residents",
        verb: {
            positive: "improve",
            negative: "deteriorate",
            },
        noun: {
            positive: "improvement",
            negative: "deteriorate",
        },
        alternative: "health_bad",
        desc: "described",
    },
    'health_fair': {
        id: 1,
        subject: "health",
        theme: 'well-being',
        topic: "health",
        topicLong: "healthy residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "healthy",
        synonym: "healthy",
        verb: {
            positive: "deteriorate",
            negative: "improve",
        },
        noun: {
            positive: "deteriorate",
            negative: "improve",
        },
        alternative: "health_good",
        desc: "described",
    },
    'health_bad': {
        id: 1,
        theme: 'well-being',
        topic: "health",
        topicLong: "healthy residents",
        topicMed: "in poor health",
        topicMed2: "in poor health",
        adjective: "healthy",
        synonym: "healthy",
        verb: {
            positive: "deteriorate",
            negative: "improve",
        },
        noun: {
            positive: "shift",
            negative: "shift",
        },
        alternative: "health_good",
        desc: "described",
    },
    'travel_car_van': {
        id: 1,
        theme: "commute",
        topic: "car commuting",
        topicLong: "residents travelling to work by car or van",
        topicMed: "commuting by car",
        topicMed2: "commute by car",
        adjective: "car-reliant",
        synonym: "driving",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "travel_foot",
        desc: "said",
    },
    'travel_foot': {
        id: 1,
        theme: "commuting method",
        topic: "walk to work",
        topicLong: "residents travelling to work by foot",
        topicMed: "commuting by foot",
        topicMed2: "walk to work",
        adjective: "pedestrian",
        synonym: "walkers",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "travel_car_van",
        desc: "said",
    },
    'travel_home': {
        id: 1,
        theme: "commuting method",
        topic: "work from home",
        topicLong: "residents primarily working from home",
        topicMed: "working from home",
        topicMed2: "work from home",
        adjective: "homeworking",
        synonym: "homeworkers",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },        
        alternative: "travel_car_van",
        desc: "said",
    },
    'travel_train_metro': {
        id: 1,
        theme: "commuting method",
        topic: "train commuting",
        topicLong: "residents travelling to work by train or metro",
        topicMed: "commuting by train",
        topicMed2: "XXXXXXXXXXX",
        adjective: "train-travelling",
        synonym: "passengers",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "travel_car_van",
        desc: "said",
    },
    'travel_bicycle': {
        id: 1,
        theme: "commuting method",
        topic: "bike commuting",
        topicLong: "residents travelling to work by bicycle",
        topicMed: "commuting by bicycle",
        topicMed2: "commuting by bicycle",
        adjective: "cyclist",
        synonym: "cyclists",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "travel_car_van",
        desc: "said",
    },  
    'age10yr_0-9': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_10-19': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_20-29': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_30-39': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_40-49': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_50-59': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_60-69': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'age10yr_70plus': {
        id: 1,
        theme: "average age",
        topic: "age",
        topicLong: "age profile",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "age",
        synonym: "10 year",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "agemed",
        desc: "said",
    },
    'ethnicity_asian': {
        id: 1,
        subject: "ethnic makeup", // applies to route subject
        theme: "average age",
        topic: "proportion of Asian residents",
        topicLong: "proportion of Asian residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "proportion of Asian residents",
        synonym: "proportion of Asian residents",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "ethnicity_white",
        desc: "said",
    },
    'ethnicity_black': {
        id: 1,
        subject: "ethnic makeup",
        theme: "average age",
        topic: "proportion of Black residents",
        topicLong: "proportion of Black residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "proportion of Black residents",
        synonym: "proportion of Black residents",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "ethnicity_white",
        desc: "said",
    },
    'ethnicity_white': {
        id: 1,
        subject: "ethnic makeup",
        theme: "average age",
        topic: "proportion of White residents",
        topicLong: "proportion of White residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "proportion of White residents",
        synonym: "proportion of White residents",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "ethnicity_black",
        desc: "said",
    },
    'ethnicity_mixed': {
        id: 1,
        subject: "ethnic makeup",
        theme: "average age",
        topic: "proportion of Mixed residents",
        topicLong: "proportion of Mixed residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "proportion of Mixed residents",
        synonym: "proportion of Mixed residents",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "ethnicity_white",
        desc: "said",
    },
    'economic_self-employed': {
        id: 1,
        theme: "average age",
        topic: "self-employment",
        topicLong: "proportion of self-employed residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "self-employed",
        synonym: "rate of self-employment",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "economic_employee",
        desc: "said",
    },
    'economic_employee': {
        id: 1,
        theme: "average age",
        topic: "rate of employment",
        topicLong: "proportion of employed residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "employed",
        synonym: "employment",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "economic_unemployed",
        desc: "said",
    },
    'economic_inactive': {
        id: 1,
        theme: "average age",
        topic: "economic inactivity",
        topicLong: "proportion of economically inactive residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "economically inactive",
        synonym: "rate of economic inactivity",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "economic_employee",
        desc: "said",
    },
    'economic_unemployed': {
        id: 1,
        theme: "average age",
        topic: "rate of unemployment",
        topicLong: "proportion of unemployed residents",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "unemployed",
        synonym: "unemployment",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "economic_employee",
        desc: "said",
    },
    'economic_student': {
        id: 1,
        theme: "average age",
        topic: "students",
        topicLong: "proportion of residents who are students",
        topicMed: "XXXXXXXXXXX",
        topicMed2: "XXXXXXXXXXX",
        adjective: "student",
        synonym: "proportion of students",
        verb: {
            positive: "increase",
            negative: "decrease",
        },
        noun: {
            positive: "increase",
            negative: "decrease",
        },
        alternative: "economic_employee",
        desc: "said",
    },
}